### ISSUE TITLE
Aspose words SDK for Ruby

### ISSUE THREAD

**Issue by RuslanKhabibullinFs** [aspose-words/Aspose.Words-for-Cloud#17]
Can't get words_api.put_convert_document. It throw exeption: Encoding::UndefinedConversionError: "\xD0" from ASCII-8BIT to UTF-8. I think api_client.rb should write file with 'wb' mode - it's fix the problem

**Comment by aspose-pdf** [comment]
Hi Ruslan Khabibullin,

Thank you for contacting Aspose support. We want to reproduce this error at our end. 

Would you please share your code and the resource file that causing this error.

**Comment by RuslanKhabibullinFs** [comment]
Hm, in Rails it throws error  
@words_api.put_convert_document(file, format: "html")
ETHON: performed EASY effective_url=http://api.aspose.cloud/v1.1/words/convert?format=html&appSID=468ff4ce-e92c-4b32-af19-17ab80bacbc0&signature=PtzyVSizGGGd5XZcc30ajW6bgtQ response_code=200 return_code=ok total_time=0.840185
Encoding::UndefinedConversionError: "\xD0" from ASCII-8BIT to UTF-8
from /home/willfarm/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/aspose_words_cloud-1.0.1/lib/aspose_words_cloud/api_client.rb:230:in `write'.

But in clear ruby script everything works fine

**Comment by RuslanKhabibullinFs** [comment]
If i change api_client code in 230 line to File.open(path, 'wb') { |file| file.write(response.body) } it's work without any errors

**Comment by aspose-pdf** [comment]
Hello Ruslan,

Thank you for getting back to us and for pointing this out. We will be updating the Ruby SDK and Gem in the near future.

Kind Regards,
Mateen Sajjad
