### ISSUE TITLE
LoadError: cannot load such file -- aspose_storage_cloud

### ISSUE THREAD

**Issue by beverlyguillermo** [aspose-words/Aspose.Words-for-Cloud#19]
Anyone using version 1.0.3 of `aspose_words_cloud` gem?  In ruby it's raising the exception
```
LoadError: cannot load such file -- aspose_storage_cloud
```

also created an issue here: https://github.com/aspose-total/Aspose.Total-for-Cloud/issues/20

**Comment by sohail-aspose** [comment]
@beverlyguillermo
 
Thanks for contacting Aspose Support.

Installing `aspose_storage_cloud` version `1.0.0` would fix this error. Please type the following command in your terminal.

`gem install aspose_storage_cloud -v 1.0.0`

Please contact us if there are any problems.

**Comment by beverlyguillermo** [comment]
Thanks for you response but will this be fixed in future releases?

**Comment by sohail-aspose** [comment]
The issue has been fixed in the current release. Now you should not face "LoadError: cannot load such file -- aspose_storage_cloud" error when you install `aspose_words_cloud` Ruby Gem.

`gem install aspose_words_cloud`

**Comment by beverlyguillermo** [comment]
Thanks it works now.
